### ISSUE TITLE
Flatpak package needs permission filesystem=host to find hugo executable

### ISSUE THREAD

**Issue by kwetal** [flathub/org.buhocms.BuhoCMS#13]
Application option [Create website] from the start screen does not find the hugo executable `/snap/bin/hugo` on my system, unless I give the BuhoCMS application the permission `filsystem=host`.

The suggested solution, to add the talk-name `org.freedesktop.Flatpak` is not sufficient, because hugo on my Ubuntu-system is not a flatpack package.

BuhoCMS `org.buhocms.BuhoCMS` version 0.5.0

Screenshot after adding both permissions `talk-name=org.freedesktop.Flatpak` and `filesystem=host`:
![After adding both permissions `talk-name=org.freedesktop.Flatpak` and `filesystem=host`](https://user-images.githubusercontent.com/6597758/231747549-9ef82a25-868e-4347-b68d-bf894ccee55a.png)

**Comment by iakmds** [comment]
Hi there, thank you a lot!

I have now changed the fileystem to host (PR https://github.com/flathub/org.buhocms.BuhoCMS/pull/14). Let me know once it is working and when we can close the issue. Also, version 0.6.0 is coming out soon on Flathub (I updated it incorrectly)

**Comment by kwetal** [comment]
Hi, following your fix, I uninstalled the buhocms package on my computer and installed it again. Then it found the hugo executable `/snap/bin/hugo` without trouble.
